% calcPSNR.m
% Calculates the PSNR between two images.
%
% Author: Josh Haskins
% Date: April 25, 2015

[peaksnr, snr] = psnr(imread(uigetfile(fullfile('' , {'*.jpg;*.jpeg;*.png;*.gif;*.tif;',...
    'Images (*.jpg,*.jpeg,*.png,*.gif,*.tif)';
    '*.jpg;*.jpeg',  'JPEG'; ...
    '*.png','PNG'; ...
    '*.gif','GIF'; ...
    '*.tif','TIF'; ...
    '*.*',  'All Files (*.*)'}), 'Select watermarked image')), imread(uigetfile(fullfile('' , {'*.jpg;*.jpeg;*.png;*.gif;*.tif;',...
    'Images (*.jpg,*.jpeg,*.png,*.gif,*.tif)';
    '*.jpg;*.jpeg',  'JPEG'; ...
    '*.png','PNG'; ...
    '*.gif','GIF'; ...
    '*.tif','TIF'; ...
    '*.*',  'All Files (*.*)'}), 'Select original image')));

fprintf('\n The Peak-SNR value is %0.4f', peaksnr);
fprintf('\n The SNR value is %0.4f \n', snr);